steps:
# Reservations
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      'us-east4-docker.pkg.dev/boomit-438919/reservations/production',
      '-f',
      'apps/reservations/Dockerfile',
      '.'
    ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'us-east4-docker.pkg.dev/boomit-438919/reservations/production',
      '-f',
      'apps/reservations/Dockerfile',
      '.'
    ]
    # Payments
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      'us-east4-docker.pkg.dev/boomit-438919/payments/production',
      '-f',
      'apps/payments/Dockerfile',
      '.'
    ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'us-east4-docker.pkg.dev/boomit-438919/payments/production',
      '-f',
      'apps/payments/Dockerfile',
      '.'
    ]
    # Notifications
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      'us-east4-docker.pkg.dev/boomit-438919/notifications/production',
      '-f',
      'apps/notifications/Dockerfile',
      '.'
    ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'us-east4-docker.pkg.dev/boomit-438919/notifications/production',
      '-f',
      'apps/notifications/Dockerfile',
      '.'
    ]
    # Auth
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      'us-east4-docker.pkg.dev/boomit-438919/auth/production',
      '-f',
      'apps/auth/Dockerfile',
      '.'
    ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'us-east4-docker.pkg.dev/boomit-438919/auth/production',
      '-f',
      'apps/auth/Dockerfile',
      '.'
    ]
options:
  logging: CLOUD_LOGGING_ONLY
